export const CREATE = 'CREATE';
export const UPDATE = 'UPDATE';
export const DELETE = 'DELETE';
export const FETCH_ALL = 'FETCH_ALL';
export const FETCH_BY_SEARCH = 'FETCH_BY_SEARCH';
export const FETCH_ROOM = 'FETCH_ROOM';
export const FETCH_ROOM_BOOK='FETCH_ROOM_BOOK';
export const END_LOADING = 'END_LOADING';
export const START_LOADING = 'START_LOADING';



export const AUTH = 'AUTH';
export const SIGNUP = 'SIGNUP';
export const LOGOUT = 'LOGOUT';
export const FETCH_NOTIFY='FETCH_NOTIFY';
export const CLEAR_NOTIFY='CLEAR_NOTIFY';
export const USER_PROFILE = 'USER_PROFILE'
export const DELETE_USER = 'DELETE_USER'
export const CHANGE_PASSWORD='CHANGE_PASSWORD'
export const UPDATE_AVAIL='UPDATE_AVAIL'
export const APPROVE_AVAIL_1='APPROVE_AVAIL_1';
export const REJECT_AVAIL_1='REJECT_AVAIL_1';
export const APPROVE_AVAIL_2='APPROVE_AVAIL_2';
export const REJECT_AVAIL_2='REJECT_AVAIL_2';
export const APPROVE_AVAIL_3='APPROVE_AVAIL_3';
export const REJECT_AVAIL_3='REJECT_AVAIL_3';
export const WITHDRAW_AVAIL='WITHDRAW_AVAIL';
export const CREATE_REQUEST='CREATE_REQUEST'
export const FETCH_REQUESTS='FETCH_REQUESTS'
export const FETCH_REQUEST='FETCH_REQUEST'
export const ACCEPT_REQUEST_1='ACCEPT_REQUEST_1'
export const REJECT_REQUEST_1='REJECT_REQUEST_1'
export const ACCEPT_REQUEST_2='ACCEPT_REQUEST_2'
export const REJECT_REQUEST_2='REJECT_REQUEST_2'
export const ACCEPT_REQUEST_3='ACCEPT_REQUEST_3'
export const REJECT_REQUEST_3='REJECT_REQUEST_3'
export const SUBMIT_EQUIP='SUBMIT_EQUIP'
export const WITHDRAW_REQUEST='WITHDRAW_REQUEST';

export const ALLUSERS='ALLUSERS';
export const FETCHBLOCKS='FETCHBLOCKS';
export const DELETEBLOCK='DELETEBLOCK';

